"use client";

import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { GithubIcon as Github } from "@/components/icons/github";
import { AppleIcon } from "@/components/icons/apple";
import { AndroidIcon } from "@/components/icons/android";
import { AnimTerminal, type TerminalLine } from "./anim-terminal";
import { siteConfig } from "@/lib/site";

const heroLines: TerminalLine[] = [
  { t: "prompt", s: "shipit generate" },
  { t: "dim", s: "⠼ Inspecting project and inferring defaults" },
  { t: "prompt", s: "Xcode scheme [MyApp]:" },
  { t: "prompt", s: "Bundle identifier [com.example.myapp]:" },
  { t: "prompt", s: "Apple Developer Team ID [A1A1A1A1A1]:" },
  { t: "prompt", s: "Do you want this Shipfile to include App Store Connect upload settings? [y/N]: y" },
  { t: "info", s: "=== App Store Connect Environment ===" },
  { t: "info", s: "ShipIt will reference env vars instead of storing secrets in Shipfile.yml." },
  { t: "info", s: "  ASC_KEY_ID             [set] App Store Connect API key ID" },
  { t: "info", s: "  ASC_ISSUER_ID          [set] ASC issuer UUID" },
  { t: "info", s: "  ASC_PRIVATE_KEY_PATH   [set] Path to .p8 key file (preferred)" },
  { t: "info", s: "  ASC_PRIVATE_KEY        (not set) Raw .p8 PEM content (CI fallback)" },
  { t: "prompt", s: "Override ASC_KEY_ID? [y/N]: no" },
  { t: "prompt", s: "Override ASC_ISSUER_ID? [y/N]: no" },
  { t: "prompt", s: "Override ASC_PRIVATE_KEY_PATH? [y/N]: no" },
  { t: "prompt", s: "ASC_PRIVATE_KEY (leave blank to skip):" },
  { t: "prompt", s: "Are you using manual code signing (.p12 + provisioning profile)? [y/N]: N" },
  { t: "info", s: "=== Shipfile Preview ===" },
  { t: "info", s: "# Shipfile.yml — generated by `shipit generate`\n..." },
];

const pills = [
  { t: "Swift 6", c: "#8B5CF6" },
  { t: "Linux", c: "#58A6FF" },
  { t: "AI-first", c: "#58A6FF" },
];

export function Hero() {
  return (
    <section className="mx-auto grid max-w-[1200px] grid-cols-1 items-center gap-12 px-6 pt-[88px] pb-20 md:grid-cols-2 md:gap-[72px]">
      <div className="fade-up">
        <h1
          className="mb-[22px] text-[42px] leading-[1.06] font-bold tracking-[-0.03em] sm:text-[54px]"
          style={{ fontFamily: "var(--font-display)", color: "var(--fg1)" }}
        >
          Start with
          <br />
          <span style={{ color: "var(--brand)" }}>shipit generate.</span>
        </h1>
        <p className="mb-9 max-w-[460px] text-[17px] leading-[1.7]" style={{ color: "var(--fg2)" }}>
          Start with <code>shipit generate</code> to build a real config from your project, reuse existing env values, and keep secrets out of <code>Shipfile.yml</code>.
        </p>
        <a
          href={siteConfig.github.cli}
          target="_blank"
          rel="noopener noreferrer"
          className="mb-6 flex max-w-[380px] items-center gap-3 rounded-lg border px-4 py-3 transition-colors"
          style={{ background: "var(--surface)", borderColor: "var(--border)" }}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = "var(--border-active)";
            e.currentTarget.style.background = "var(--elevated)";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = "var(--border)";
            e.currentTarget.style.background = "var(--surface)";
          }}
        >
          <div
            className="flex h-8 w-8 items-center justify-center rounded-lg"
            style={{ background: "var(--brand-muted)", color: "var(--brand)" }}
          >
            <Github size={15} />
          </div>
          <div className="min-w-0 flex-1">
            <div
              className="text-[11px] tracking-[0.08em] uppercase"
              style={{ color: "var(--fg3)" }}
            >
              Open source
            </div>
            <div className="truncate text-[13px]" style={{ color: "var(--fg1)" }}>
              Browse ShipItSwifty on GitHub
            </div>
          </div>
          <ArrowUpRight size={15} style={{ color: "var(--fg3)" }} />
        </a>
        <div className="flex flex-wrap gap-3">
          <Link
            href="/docs"
            className="inline-block rounded-md px-[22px] py-2.5 text-[15px] font-medium text-white transition-colors"
            style={{
              background: "var(--brand)",
              border: "1px solid var(--brand)",
              fontFamily: "var(--font-body)",
            }}
            onMouseEnter={(e) => (e.currentTarget.style.background = "var(--brand-hover)")}
            onMouseLeave={(e) => (e.currentTarget.style.background = "var(--brand)")}
          >
            Get Started
          </Link>
        </div>
        <p className="mt-4 text-[13px] leading-[1.65]" style={{ color: "var(--fg3)" }}>
          ⚠️ Beta release. For feedback, bug reports, and feature requests, open an issue in{" "}
          <a
            href={`${siteConfig.github.cli}/issues`}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "var(--blue)" }}
          >
            GitHub Issues
          </a>
          .
        </p>
        <div className="mt-5 flex flex-wrap gap-2">
          <span
            className="inline-flex items-center justify-center gap-1.5 rounded-full border px-2.5 py-[3px] text-xs font-medium"
            aria-label="iOS and Android"
            title="iOS and Android"
            style={{
              color: "var(--fg1)",
              background: "#3FB95018",
              borderColor: "#3FB95055",
              fontFamily: "var(--font-body)",
            }}
          >
            <span style={{ color: "var(--fg1)" }}>
              <AppleIcon size={14} aria-hidden />
            </span>
            <span aria-hidden style={{ color: "var(--fg3)", lineHeight: 1 }}>
              +
            </span>
            <span style={{ color: "#3DDC84" }}>
              <AndroidIcon size={14} aria-hidden />
            </span>
            <span className="sr-only">iOS and Android</span>
          </span>
          {pills.map((p) => (
            <span
              key={p.t}
              className="rounded-full border px-2.5 py-[3px] text-xs font-medium"
              style={{
                color: "var(--fg1)",
                background: `${p.c}18`,
                borderColor: `${p.c}55`,
                fontFamily: "var(--font-body)",
              }}
            >
              <span
                aria-hidden
                className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full align-middle"
                style={{ background: p.c }}
              />
              {p.t}
            </span>
          ))}
        </div>
      </div>
      <div className="fade-up-delayed">
        <AnimTerminal lines={heroLines} loopMs={8000} lineMode="wrap" />
      </div>
    </section>
  );
}
